"""Case intake, state, and an in-process registry shared by the web routes.

The web GUI collects plain-language case context plus evidence paths, and this module turns
that into:

* a :class:`CaseState` — the JSON-serializable status the GUI polls, and
* a :class:`~linuxir.config.CaseConfig` — the evidence-scope / workspace contract the rest of
  the pipeline (gateway, enforcer, agents, report) already speaks.

It also writes the first vault note, ``Evidence/case-state.md``, through the
:class:`~linuxir.obsidian.ObsidianServer`. That note appearing in Obsidian is the Day-1 gate.
"""

from __future__ import annotations

import os
import uuid
from datetime import datetime, timezone
from pathlib import Path

from pydantic import BaseModel, Field

from .config import CaseConfig
from .obsidian import ObsidianServer


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _slug(text: str) -> str:
    keep = [c.lower() if c.isalnum() else "-" for c in text.strip()]
    s = "".join(keep).strip("-")
    while "--" in s:
        s = s.replace("--", "-")
    return s[:32] or "case"


def detect_source_type(path: Path) -> str:
    """Cheap, syntactic source-type guess (the agents refine this during triage)."""
    if path.is_dir():
        name = path.name.lower()
        if name in {"log", "logs"} or (path / "auth.log").exists():
            return "log_directory"
        return "mounted_image"
    suffix = path.suffix.lower()
    if suffix in {".pcap", ".pcapng", ".cap"}:
        return "pcap"
    if suffix in {".lime", ".mem", ".raw", ".vmem", ".dump", ".lmem"}:
        return "memory_capture"
    if suffix in {".log", ".journal"} or path.name in {"auth.log", "syslog", "wtmp", "btmp"}:
        return "log_file"
    if suffix in {".img", ".dd", ".e01", ".raw"}:
        return "raw_disk"
    return "unknown"


class CaseIntake(BaseModel):
    """What the browser form posts to ``POST /case/new``."""

    client_name: str = Field(..., min_length=1)
    industry: str = ""
    suspected_breach_date: str | None = None
    context: str = ""
    evidence_paths: list[str] = Field(..., min_length=1)
    workspace: str | None = None  # default: $CASE_DIR/{case_id}


class CaseState(BaseModel):
    """Live status the GUI renders. Mirrors CLAUDE.md Section 3's CaseState (intake subset)."""

    case_id: str
    client_name: str
    industry: str = ""
    suspected_breach_date: str | None = None
    context: str = ""
    sources: list[dict]  # [{"path","type","exists"}]
    workspace: str
    phase: str = "intake"  # intake -> triage -> analysis -> audit -> expert -> persona -> report -> complete
    iteration: int = 0
    max_iterations: int = 10
    findings_count: int = 0
    high_confidence_count: int = 0
    obsidian_transport: str = "local"  # where case-state.md landed
    note_path: str = ""
    created_at: datetime
    updated_at: datetime


def _case_state_md(state: CaseState) -> str:
    src_lines = "\n".join(
        f"- `{s['path']}` — **{s['type']}** "
        f"({'found' if s['exists'] else '⚠️ not found at intake'})"
        for s in state.sources
    )
    return (
        f"# Case `{state.case_id}` — case state\n\n"
        f"- **Client:** {state.client_name}\n"
        f"- **Industry:** {state.industry or '—'}\n"
        f"- **Suspected breach date:** {state.suspected_breach_date or '—'}\n"
        f"- **Phase:** {state.phase}\n"
        f"- **Iteration:** {state.iteration}/{state.max_iterations}\n"
        f"- **Created (UTC):** {state.created_at.isoformat()}\n"
        f"- **Updated (UTC):** {state.updated_at.isoformat()}\n\n"
        f"## Context\n\n{state.context or '_No context provided._'}\n\n"
        f"## Evidence sources\n\n{src_lines or '_None._'}\n\n"
        f"## Findings\n\n"
        f"- Recorded: {state.findings_count}\n"
        f"- HIGH-confidence: {state.high_confidence_count}\n\n"
        f"---\n_Generated by LinuxIR Agent. Read-only investigation; "
        f"evidence is never modified._\n"
    )


class CaseEntry:
    """A case's runtime bundle: its state, config, and Obsidian writer."""

    def __init__(self, state: CaseState, config: CaseConfig, obsidian: ObsidianServer) -> None:
        self.state = state
        self.config = config
        self.obsidian = obsidian


class CaseStore:
    """In-process registry of cases. One per server process; survives across requests."""

    def __init__(self, case_dir: Path | None = None) -> None:
        self.case_dir = Path(case_dir or os.getenv("CASE_DIR", "./out")).resolve()
        self._cases: dict[str, CaseEntry] = {}

    def create(self, intake: CaseIntake) -> CaseEntry:
        case_id = f"{_slug(intake.client_name)}-{uuid.uuid4().hex[:6]}"
        workspace = (
            Path(intake.workspace).resolve()
            if intake.workspace
            else self.case_dir / case_id
        )

        sources = []
        scope: list[Path] = []
        for raw in intake.evidence_paths:
            p = Path(raw).expanduser().resolve()
            sources.append({"path": str(p), "type": detect_source_type(p), "exists": p.exists()})
            scope.append(p)

        config = CaseConfig(case_id=case_id, evidence_scope=tuple(scope), workspace=workspace)
        config.ensure_workspace()

        now = _now()
        state = CaseState(
            case_id=case_id,
            client_name=intake.client_name,
            industry=intake.industry,
            suspected_breach_date=intake.suspected_breach_date,
            context=intake.context,
            sources=sources,
            workspace=str(workspace),
            max_iterations=int(os.getenv("MAX_ITERATIONS", "10")),
            created_at=now,
            updated_at=now,
        )

        obsidian = ObsidianServer(case_id=case_id, fallback_root=config.vault_path)
        res = obsidian.write("Evidence/case-state.md", _case_state_md(state))
        state.obsidian_transport = res.transport
        state.note_path = res.path

        entry = CaseEntry(state, config, obsidian)
        self._cases[case_id] = entry
        return entry

    def get(self, case_id: str) -> CaseEntry | None:
        return self._cases.get(case_id)

    def list_ids(self) -> list[str]:
        return list(self._cases.keys())

    def touch(self, case_id: str) -> None:
        """Re-render and persist the case-state note after a state change."""
        entry = self._cases.get(case_id)
        if not entry:
            return
        entry.state.updated_at = _now()
        res = entry.obsidian.write("Evidence/case-state.md", _case_state_md(entry.state))
        entry.state.obsidian_transport = res.transport
        entry.state.note_path = res.path
